#!/bin/bash

# Auto-generate settings.md from settings.json
# Runs as a PostToolUse hook - zero Claude tokens

SETTINGS_JSON=".claude/settings.json"
SETTINGS_MD=".claude/settings.md"

# Only run if settings.json was modified in this git session
if ! git diff --name-only --cached 2>/dev/null | grep -q "$SETTINGS_JSON" && \
   ! git diff --name-only 2>/dev/null | grep -q "$SETTINGS_JSON"; then
  exit 0
fi

# Generate the markdown documentation
cat > "$SETTINGS_MD" << 'HEADER'
# Claude Settings Documentation

This document is **auto-generated** from `settings.json`. Do not edit directly.

---

## Hooks

Hooks allow Claude to automatically run commands at specific points during tool execution.

### PostToolUse Hooks

These hooks run **after** Claude finishes using a tool.

HEADER

# Parse hooks from JSON using jq (if available) or basic parsing
if command -v jq &> /dev/null; then
  # Use jq for proper JSON parsing
  jq -r '.hooks.PostToolUse[]? | "| **Hook** | `\(.matcher)` | `\(.hooks[0].command)` |"' "$SETTINGS_JSON" 2>/dev/null | while read -r line; do
    if [ -n "$line" ]; then
      echo "| Trigger Tools | Action |" >> "$SETTINGS_MD"
      echo "| ------------- | ------ |" >> "$SETTINGS_MD"
      echo "$line" >> "$SETTINGS_MD"
    fi
  done
else
  # Fallback: just embed the raw JSON
  echo '```json' >> "$SETTINGS_MD"
  cat "$SETTINGS_JSON" >> "$SETTINGS_MD"
  echo '```' >> "$SETTINGS_MD"
fi

cat >> "$SETTINGS_MD" << 'FOOTER'

---

## Configuration File

See `settings.json` for the machine-readable configuration.

---

*Auto-generated by `.claude/hooks/update-settings-docs.sh`*
FOOTER

# Stage the updated docs
git add "$SETTINGS_MD" 2>/dev/null || true

echo "✓ Updated settings.md"
